return {
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageConcrete", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{652031557782, --[[ModItemBuildingTemplate StorageConcrete pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{555828323351, --[[ModItemBuildingTemplate StorageConcrete pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageConcrete_ExtraStorage", 
        'upgrade1_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageConcrete upgrade1_display_name]] "Expand Storage"}, 
        'upgrade1_description', T{162309256812, --[[ModItemBuildingTemplate StorageConcrete upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageConcrete", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageConcrete_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageConcrete upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageConcrete upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageConcrete", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageConcrete_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageConcrete upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageConcrete upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageConcrete", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{806209022008, --[[ModItemBuildingTemplate StorageConcrete display_name]] "Upgradeable Concrete Depot"}, 
        'display_name_pl', T{434373388403, --[[ModItemBuildingTemplate StorageConcrete display_name_pl]] "Upgradeable Concrete Depots"}, 
        'description', T{756993657160, --[[ModItemBuildingTemplate StorageConcrete description]] "Stores <concrete(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/concrete_storage_upgrade.tga", 
        'build_pos', 3, 
        'entity', "StorageDepotSmall_03", 
        'encyclopedia_image', "UI/Encyclopedia/ConcreteDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Concrete", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageElectronics", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{120857444882, --[[ModItemBuildingTemplate StorageElectronics pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{974455519337, --[[ModItemBuildingTemplate StorageElectronics pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageElectronics_ExtraStorage", 
        'upgrade1_display_name', T{395631787612, --[[ModItemBuildingTemplate StorageElectronics upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{272079127224, --[[ModItemBuildingTemplate StorageElectronics upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageElectronics", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageElectronics_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageElectronics upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageElectronics upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageElectronics", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageElectronics_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageElectronics upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageElectronics upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageElectronics", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{282723376622, --[[ModItemBuildingTemplate StorageElectronics display_name]] "Upgradeable Electronics Depot"}, 
        'display_name_pl', T{392318834565, --[[ModItemBuildingTemplate StorageElectronics display_name_pl]] "Upgradeable Electronics Depots"}, 
        'description', T{938410302462, --[[ModItemBuildingTemplate StorageElectronics description]] "Stores <electronics(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/electronics_storage_upgrade.tga", 
        'build_pos', 7, 
        'entity', "StorageDepotSmall_08", 
        'encyclopedia_image', "UI/Encyclopedia/ElectronicsDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Electronics", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageFood", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{590189655090, --[[ModItemBuildingTemplate StorageFood pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{229899625194, --[[ModItemBuildingTemplate StorageFood pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageFood_ExtraStorage", 
        'upgrade1_display_name', T{350165656564, --[[ModItemBuildingTemplate StorageFood upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{935851595680, --[[ModItemBuildingTemplate StorageFood upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageFood", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageFood_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageFood upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageFood upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageFood", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageFood_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageFood upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageFood upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageFood", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{354163898645, --[[ModItemBuildingTemplate StorageFood display_name]] "Upgradeable Food Depot"}, 
        'display_name_pl', T{468769072438, --[[ModItemBuildingTemplate StorageFood display_name_pl]] "Upgradeable Food Depots"}, 
        'description', T{639459637449, --[[ModItemBuildingTemplate StorageFood description]] "Stores <food(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/food_storage_upgrade.tga", 
        'build_pos', 4, 
        'entity', "StorageDepotSmall_04", 
        'encyclopedia_image', "UI/Encyclopedia/FoodDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Food", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageFuel", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{197442968333, --[[ModItemBuildingTemplate StorageFuel pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{992138499241, --[[ModItemBuildingTemplate StorageFuel pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageFuel_ExtraStorage", 
        'upgrade1_display_name', T{402830188100, --[[ModItemBuildingTemplate StorageFuel upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{781864000147, --[[ModItemBuildingTemplate StorageFuel upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageFuel", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageFuel_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageFuel upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageFuel upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageFuel", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageFuel_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageFuel upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageFuel upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageFuel", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{850876854952, --[[ModItemBuildingTemplate StorageFuel display_name]] "Upgradeable Fuel Depot"}, 
        'display_name_pl', T{345923557719, --[[ModItemBuildingTemplate StorageFuel display_name_pl]] "Upgradeable Fuel Depots"}, 
        'description', T{683138207573, --[[ModItemBuildingTemplate StorageFuel description]] "Stores <fuel(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/fuel_storage_upgrade.tga", 
        'build_pos', 9, 
        'entity', "StorageDepotSmall_06", 
        'encyclopedia_image', "UI/Encyclopedia/FuelDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Fuel", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageMachineParts", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{939862488054, --[[ModItemBuildingTemplate StorageMachineParts pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{749155873332, --[[ModItemBuildingTemplate StorageMachineParts pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageMachineParts_ExtraStorage", 
        'upgrade1_display_name', T{176642280475, --[[ModItemBuildingTemplate StorageMachineParts upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{948924314130, --[[ModItemBuildingTemplate StorageMachineParts upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageMachineParts", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageMachineParts_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageMachineParts upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageMachineParts upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageMachineParts", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageMachineParts_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageMachineParts upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageMachineParts upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageMachineParts", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{677930287972, --[[ModItemBuildingTemplate StorageMachineParts display_name]] "Upgradeable Machine Parts Depot"}, 
        'display_name_pl', T{802362124083, --[[ModItemBuildingTemplate StorageMachineParts display_name_pl]] "Upgradeable Machine Parts Depots"}, 
        'description', T{751522112171, --[[ModItemBuildingTemplate StorageMachineParts description]] "Stores <machineparts(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/machine_parts_storage_upgrade.tga", 
        'build_pos', 8, 
        'entity', "StorageDepotSmall_05", 
        'encyclopedia_image', "UI/Encyclopedia/MachinePartsDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "MachineParts", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageMetals", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{951045883695, --[[ModItemBuildingTemplate StorageMetals pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{148389195761, --[[ModItemBuildingTemplate StorageMetals pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageMetals_ExtraStorage", 
        'upgrade1_display_name', T{659728619699, --[[ModItemBuildingTemplate StorageMetals upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{674078438930, --[[ModItemBuildingTemplate StorageMetals upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageMetals", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageMetals_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageMetals upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageMetals upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageMetals", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageMetals_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageMetals upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageMetals upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageMetals", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{806955136803, --[[ModItemBuildingTemplate StorageMetals display_name]] "Upgradeable Metals Depot"}, 
        'display_name_pl', T{779895985173, --[[ModItemBuildingTemplate StorageMetals display_name_pl]] "Upgradeable Metals Depots"}, 
        'description', T{863549667881, --[[ModItemBuildingTemplate StorageMetals description]] "Stores <metals(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/metal_storage_upgrade.tga", 
        'build_pos', 2, 
        'entity', "StorageDepotSmall_02", 
        'encyclopedia_image', "UI/Encyclopedia/MetalsDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Metals", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StoragePolymers", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{280847379884, --[[ModItemBuildingTemplate StoragePolymers pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{282185964867, --[[ModItemBuildingTemplate StoragePolymers pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StoragePolymers_ExtraStorage", 
        'upgrade1_display_name', T{834295731379, --[[ModItemBuildingTemplate StoragePolymers upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{129425747582, --[[ModItemBuildingTemplate StoragePolymers upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StoragePolymers", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StoragePolymers_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StoragePolymers upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StoragePolymers upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StoragePolymers", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StoragePolymers_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StoragePolymers upgrade3_display_name]] "Spherical Resource Containers"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StoragePolymers upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StoragePolymers", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{707641319543, --[[ModItemBuildingTemplate StoragePolymers display_name]] "Upgradeable Polymers Depot"}, 
        'display_name_pl', T{425219459415, --[[ModItemBuildingTemplate StoragePolymers display_name_pl]] "Upgradeable Polymers Depots"}, 
        'description', T{806002889549, --[[ModItemBuildingTemplate StoragePolymers description]] "Stores <polymers(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/polymers_storage_upgrade.tga", 
        'build_pos', 6, 
        'entity', "StorageDepotSmall_01", 
        'encyclopedia_image', "UI/Encyclopedia/PolymersDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "Polymers", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "StorageRareMetals", 
        'template_class', "UniversalStorageDepot", 
        'pin_rollover_hint', T{772949791068, --[[ModItemBuildingTemplate StorageRareMetals pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{884549026443, --[[ModItemBuildingTemplate StorageRareMetals pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'hide_from_build_menu', true, 
        'upgrade1_id', "StorageRareMetals_ExtraStorage", 
        'upgrade1_display_name', T{964726289799, --[[ModItemBuildingTemplate StorageRareMetals upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{834540050795, --[[ModItemBuildingTemplate StorageRareMetals upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "StorageRareMetals", 
        'upgrade1_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade1_add_value_1', 180, 
        'upgrade2_id', "StorageRareMetals_ExtraStorage_2", 
        'upgrade2_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageRareMetals upgrade2_display_name]] "New Stacking Methods"}, 
        'upgrade2_description', T{162309256812, --[[ModItemBuildingTemplate StorageRareMetals upgrade2_description]] "+<upgrade2_add_value_1> Storage Space. Although our contact with Earth has been sporadic for some time now, a secret transmission caught late last night brought with it a new revolutionary storage method for stacking our precious Martian resources closer to each other. No, for real, who dares dreaming of stacking methods?"}, 
        'upgrade2_icon', "UI/Icons/Upgrades/hygroscopic_coating_01.tga", 
        'upgrade2_upgrade_cost_Concrete', 10000, 
        'upgrade2_upgrade_time', 60000, 
        'upgrade2_mod_label_1', "StorageRareMetals", 
        'upgrade2_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade2_add_value_1', 180, 
        'upgrade3_id', "StorageRareMetals_ExtraStorage_3", 
        'upgrade3_display_name', T{773703751239, --[[ModItemBuildingTemplate StorageRareMetals upgrade3_display_name]] "Extra Extra Storage"}, 
        'upgrade3_description', T{162309256812, --[[ModItemBuildingTemplate StorageRareMetals upgrade3_description]] "+<upgrade3_add_value_1> Storage Space. How often did you open your container and it was only half-full (or half-empty)? No more. An all Mars invention, Spherical Containers. They constantly wrap themselves dynamically around resources to keep them protected and safe in our storage depots all the while taking as little space as possible. Why didn't we think of that earlier? It was as simple as that to increase the storage capacity, but it never crossed our minds. Until now, that is!"}, 
        'upgrade3_icon', "UI/Icons/Upgrades/magnetic_filtering_01.tga", 
        'upgrade3_upgrade_cost_Concrete', 10000, 
        'upgrade3_upgrade_time', 60000, 
        'upgrade3_mod_label_1', "StorageRareMetals", 
        'upgrade3_mod_prop_id_1', "max_storage_per_resource", 
        'upgrade3_add_value_1', 180, 
        'display_name', T{793588514451, --[[ModItemBuildingTemplate StorageRareMetals display_name]] "Upgradeable Rare Metals Depot"}, 
        'display_name_pl', T{217851185374, --[[ModItemBuildingTemplate StorageRareMetals display_name_pl]] "Upgradeable Rare Metals Depots"}, 
        'description', T{909738725237, --[[ModItemBuildingTemplate StorageRareMetals description]] "Stores <preciousmetals(max_storage_per_resource)>. Excess resources will be delivered automatically to other depots within Drone range."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/rare_metals_storage_upgrade.tga", 
        'build_pos', 5, 
        'entity', "StorageDepotSmall_07", 
        'encyclopedia_image', "UI/Encyclopedia/RareMetalsDepot.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'max_storage_per_resource', 180000, 
        'max_x', 12, 
        'storable_resources', {
            "PreciousMetals", 
        }, 
    }), 
    PlaceObj('ModItemBuildingTemplate', {
        'name', "WasteRockDumpSmall", 
        'template_class', "WasteRockDumpSite", 
        'pin_rollover_hint', T{253430560110, --[[ModItemBuildingTemplate WasteRockDumpSmall pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"}, 
        'pin_rollover_hint_xbox', T{978590171635, --[[ModItemBuildingTemplate WasteRockDumpSmall pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"}, 
        'build_points', 0, 
        'instant_build', true, 
        'dome_forbidden', true, 
        'upgrade1_id', "WasteRockDumpSite_ExtraStorage", 
        'upgrade1_display_name', T{503751464115, --[[ModItemBuildingTemplate WasteRockDumpSmall upgrade1_display_name]] "Extra Storage"}, 
        'upgrade1_description', T{932023317152, --[[ModItemBuildingTemplate WasteRockDumpSmall upgrade1_description]] "+<upgrade1_add_value_1> Storage Space. Due to the lack of space in space, we have decided to use all 9 dimensions and expand the area covered by this storage depot."}, 
        'upgrade1_icon', "UI/Icons/Upgrades/magnetic_extraction_01.tga", 
        'upgrade1_upgrade_cost_Concrete', 10000, 
        'upgrade1_upgrade_time', 60000, 
        'upgrade1_mod_label_1', "WasteRockDumpSite", 
        'upgrade1_mod_prop_id_1', "max_amount_WasteRock", 
        'upgrade1_add_value_1', 70, 
        'display_name', T{759038059070, --[[ModItemBuildingTemplate WasteRockDumpSmall display_name]] "Upgradeable Dump Site"}, 
        'display_name_pl', T{324736921511, --[[ModItemBuildingTemplate WasteRockDumpSmall display_name_pl]] "Upgradeable Dumping Sites"}, 
        'description', T{563281929874, --[[ModItemBuildingTemplate WasteRockDumpSmall description]] "Stores <wasterock(max_amount_WasteRock)>. Waste Rock is produced as side product of different mining activities."}, 
        'build_category', "Storages", 
        'display_icon', "UI/Icons/Buildings/dumping_site_upgrade.tga", 
        'build_pos', 10, 
        'entity', "WasteRockDepotBig", 
        'encyclopedia_image', "UI/Encyclopedia/DumpingSite.tga", 
        'on_off_button', false, 
        'prio_button', false, 
        'color_modifier', RGBA(122, 85, 8, 255), 
        'demolish_sinking', range(15, 30), 
        'demolish_tilt_angle', range(300, 600), 
        'exclude_from_lr_transportation', true, 
        'max_amount_WasteRock', 70000, 
    }), 
    PlaceObj('ModItemCode', {
        'name', "PostBuildingUpgradeScript", 
        'FileName', "Code/PostBuildingUpgradeScript.lua", 
    }), 
    PlaceObj('ModItemCode', {
        'name', "customWasteRockDumpSmall", 
        'FileName', "Code/customWasteRockDumpSmall.lua", 
    }), 
}
